<?php

class bigsearchHelper extends Helper {
    var $sql_text;
    var $id_current_object;
    var $name_current_object;
    var $data;
    var $messageErrorSearch;
    var $displayListSearch; 
    
    public function ShowBigSearchPanel() {
        $this->drawBlock("bigsearch", "bigsearch");
    }

    public function showBigSearchResults() {
        $this->drawBlock("bigsearch", "results", array($this->data, 
                                                       $this->messageErrorSearch,
                                                       $this->displayListSearch));
    }
    
    /*
    public function showBigSearchTemplate() {
        $this->drawBlock("bigsearch", "template", array($this->id_current_object,
                                                        $this->name_current_object,
                                                        $this->sql_text));
    }
*/
    public function BlockNavigationChain($doc_id, $doc_name)
    {
        $parents_path = $this->parents_path;
        /* получение списка родителей */
        if (empty($this->parents_path)) {
            $array_parents[0]['id'] = $doc_id;
            $array_parents[0]['name'] = $doc_name;
        }
        else {
            //получение пути
            $path = explode(';;', $parents_path['path']);
            //получение элементов пути
            foreach ($path as $element) {
                $array_parents[] = explode(':', $element);
            }
            foreach ($array_parents as $key => $value) {
                $array_parents[$key]['id'] = $value[0];
                $array_parents[$key]['type_object'] = _fw_translate_type_object($value[1], 'eng');
                $array_parents[$key]['name'] = $value[2];
                unset($array_parents[$key][0]);
                unset($array_parents[$key][1]);
                unset($array_parents[$key][2]);
            }

            if ($doc_name) {
                $array_parents[count($array_parents)+1]['id'] = $doc_id;
                $array_parents[count($array_parents)]['name'] = $doc_name;
                $array_parents[count($array_parents)]['type_object'] = 'database';
            }
        }

        $this->array_parents_object = $array_parents;

        //parent::BlockNavigationChain($template); // TODO: Change the autogenerated stub
        return var_dump($this->array_parents_object);
    }
    

    
}