<?php

class databaseHelper extends Helper {

    var $id_current; // текущий объект
    var $name_current_object; // имя текущего объекта
    var $name_database; // имя базы данных

    var $button_insert; //отображение конпки "Вставить из буфера"

    function __construct() {
    }

    public function BlockSearch() {
        $this->form_search['search-in-first-parent'] = 'В текущей базе данных';
        parent::BlockSearch();
    }

    public function BlockNavigationChain($template = 'default')
    {
        $parents_path = $this->parents_path;
        /* получение списка родителей */
        if (empty($this->parents_path)) {
            $array_parents[0]['id'] = $this->id_current_object;
            $array_parents[0]['name'] = $this->name_current_object;
        }
        else {
            //получение пути
            $path = explode(';;', $parents_path['path']);
            //получение элементов пути
            foreach ($path as $element) {
                $array_parents[] = explode(':', $element);
            }
            foreach ($array_parents as $key => $value) {
                $array_parents[$key]['id'] = $value[0];
                $array_parents[$key]['type_object'] = _fw_translate_type_object($value[1], 'eng');
                $array_parents[$key]['name'] = $value[2];
                unset($array_parents[$key][0]);
                unset($array_parents[$key][1]);
                unset($array_parents[$key][2]);
            }

            $array_parents[count($array_parents)+1]['id'] = $this->id_current_object;
            $array_parents[count($array_parents)]['name'] = $this->name_current_object;
            $array_parents[count($array_parents)]['type_object'] = 'database';

        }

        $this->array_parents_object = $array_parents;

        parent::BlockNavigationChain($template); // TODO: Change the autogenerated stub
    }
}



/**
 * Created by PhpStorm.
 * User: Kodix
 * Date: 03.06.2016
 * Time: 12:24
 */